/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppCalendarIndexRouteImport } from './routes/app/calendar/index'
import { Route as AppCalendarCalendarIdRouteImport } from './routes/app/calendar/$calendarId'
import { Route as AppAccountAccountViewRouteImport } from './routes/app/account/$accountView'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarIndexRoute = AppCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCalendarCalendarIdRoute = AppCalendarCalendarIdRouteImport.update({
  id: '/calendar/$calendarId',
  path: '/calendar/$calendarId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAccountAccountViewRoute = AppAccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/$authView': typeof AuthAuthViewRoute
  '/app/account/$accountView': typeof AppAccountAccountViewRoute
  '/app/calendar/$calendarId': typeof AppCalendarCalendarIdRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/$authView': typeof AuthAuthViewRoute
  '/app/account/$accountView': typeof AppAccountAccountViewRoute
  '/app/calendar/$calendarId': typeof AppCalendarCalendarIdRoute
  '/app/calendar': typeof AppCalendarIndexRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/auth/$authView': typeof AuthAuthViewRoute
  '/app/account/$accountView': typeof AppAccountAccountViewRoute
  '/app/calendar/$calendarId': typeof AppCalendarCalendarIdRoute
  '/app/calendar/': typeof AppCalendarIndexRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth/$authView'
    | '/app/account/$accountView'
    | '/app/calendar/$calendarId'
    | '/app/calendar'
    | '/app/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth/$authView'
    | '/app/account/$accountView'
    | '/app/calendar/$calendarId'
    | '/app/calendar'
    | '/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth/$authView'
    | '/app/account/$accountView'
    | '/app/calendar/$calendarId'
    | '/app/calendar/'
    | '/app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthAuthViewRoute: typeof AuthAuthViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calendar/': {
      id: '/app/calendar/'
      path: '/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/calendar/$calendarId': {
      id: '/app/calendar/$calendarId'
      path: '/calendar/$calendarId'
      fullPath: '/app/calendar/$calendarId'
      preLoaderRoute: typeof AppCalendarCalendarIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/account/$accountView': {
      id: '/app/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/app/account/$accountView'
      preLoaderRoute: typeof AppAccountAccountViewRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAccountAccountViewRoute: typeof AppAccountAccountViewRoute
  AppCalendarCalendarIdRoute: typeof AppCalendarCalendarIdRoute
  AppCalendarIndexRoute: typeof AppCalendarIndexRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAccountAccountViewRoute: AppAccountAccountViewRoute,
  AppCalendarCalendarIdRoute: AppCalendarCalendarIdRoute,
  AppCalendarIndexRoute: AppCalendarIndexRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthAuthViewRoute: AuthAuthViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
